# Generated by Django 5.1.15 on 2026-08-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('subject', models.CharField(max_length=200)),
                ('service_interested', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('NEW', 'New Inquiry'), ('READ', 'Read'), ('REPLIED', 'Replied'), ('CLOSED', 'Closed')], default='NEW', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
