# Generated by Django 5.1.15 on 2026-08-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Md. Alam Hossain', max_length=150)),
                ('site_title_suffix', models.CharField(default='HR & Payroll Specialist | Data Analyst | Django Developer', max_length=255)),
                ('hero_headline', models.CharField(default='Turning HR, Payroll & Workforce Data Into Smarter Business Decisions.', max_length=255)),
                ('hero_subheadline', models.TextField(default='HR and payroll professional with deep expertise in workforce management, payroll processing, HRIS, SQL reporting, data analytics, and modern Django automation.')),
                ('about_intro', models.TextField(default='I connect People + Payroll + Data + Technology to streamline HR operations and engineer resilient software solutions.')),
                ('primary_email', models.EmailField(default='contact@alamhossain.com', max_length=254)),
                ('phone', models.CharField(default='+880 1700-000000', max_length=50)),
                ('whatsapp_number', models.CharField(default='8801700000000', help_text='International format without + or special characters', max_length=50)),
                ('address', models.CharField(default='Dhaka, Bangladesh', max_length=255)),
                ('footer_statement', models.TextField(default='Connecting People, Payroll, Data & Technology to drive organizational productivity.')),
                ('seo_meta_description', models.TextField(default='Portfolio of Md. Alam Hossain - Senior HR & Payroll Specialist, HRIS Consultant, SQL Data Analyst, and Full-Stack Django Developer.')),
                ('google_analytics_id', models.CharField(blank=True, max_length=50, null=True)),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resume/')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('years_experience', models.PositiveIntegerField(default=6)),
                ('projects_completed', models.PositiveIntegerField(default=25)),
                ('reports_dashboards_developed', models.PositiveIntegerField(default=80)),
                ('hr_processes_automated', models.PositiveIntegerField(default=15)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('linkedin', 'LinkedIn'), ('github', 'GitHub'), ('facebook', 'Facebook'), ('twitter', 'Twitter/X'), ('whatsapp', 'WhatsApp')], max_length=30)),
                ('url', models.URLField()),
                ('icon_class', models.CharField(help_text='e.g., bi bi-linkedin or fa-brands fa-linkedin', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_path', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['visited_at', 'page_path'], name='core_pagevi_visited_74ac27_idx')],
            },
        ),
    ]
