# Generated by Django 5.1.15 on 2026-08-16 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('metric_value', models.CharField(help_text='e.g., 99.8%, 10x, 2,500+ Manpower', max_length=50)),
                ('description', models.TextField()),
                ('category', models.CharField(default='Payroll Automation', max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('domain_tag', models.CharField(default='Payroll Optimization', max_length=100)),
                ('problem', models.TextField()),
                ('solution', models.TextField()),
                ('results', models.TextField()),
                ('tools_used', models.CharField(default='SQL Server, Python, Django, Excel', max_length=255)),
                ('is_featured', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Case Studies',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issuing_organization', models.CharField(max_length=150)),
                ('issue_date', models.DateField()),
                ('credential_id', models.CharField(blank=True, max_length=100, null=True)),
                ('credential_url', models.URLField(blank=True, null=True)),
                ('certificate_image', models.ImageField(blank=True, null=True, upload_to='certificates/')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=150)),
                ('institution', models.CharField(max_length=200)),
                ('major', models.CharField(max_length=150)),
                ('start_year', models.PositiveIntegerField()),
                ('completion_year', models.PositiveIntegerField(blank=True, null=True)),
                ('result', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('institution_logo', models.ImageField(blank=True, null=True, upload_to='education/')),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Education',
                'ordering': ['display_order', '-start_year'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=150)),
                ('position', models.CharField(max_length=150)),
                ('location', models.CharField(default='Dhaka, Bangladesh', max_length=150)),
                ('department', models.CharField(default='HR & Administration', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('responsibilities', models.TextField(help_text='Detailed responsibilities. Use new lines for bullets.')),
                ('achievements', models.TextField(help_text='Key measurable outcomes delivered.')),
                ('technologies_used', models.CharField(help_text='e.g. MS SQL Server, Django, Biometric Systems, Advanced Excel', max_length=255)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='companies/')),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Project Categories',
            },
        ),
        migrations.CreateModel(
            name='ResumeDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('icon_class', models.CharField(default='bi bi-cpu', max_length=60)),
                ('short_description', models.CharField(max_length=255)),
                ('detailed_description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon_class', models.CharField(default='bi bi-gear', max_length=60)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Skill Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('badge_class', models.CharField(default='bg-secondary', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Technologies',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('content', models.TextField()),
                ('rating', models.PositiveIntegerField(default=5)),
                ('is_featured', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('thumbnail', models.ImageField(upload_to='projects/')),
                ('summary', models.TextField(help_text='Concise 2-sentence executive summary.')),
                ('business_challenge', models.TextField(help_text='Detailed problem faced by business/HR.')),
                ('engineered_solution', models.TextField(help_text='Architectural/Technical solution developed.')),
                ('key_features', models.TextField(help_text='Markdown or bullet list of implemented functionalities.')),
                ('business_impact', models.TextField(help_text='Measurable business results, efficiency gains, accuracy improvements.')),
                ('role', models.CharField(default='Lead Developer & HR Systems Architect', max_length=150)),
                ('duration', models.CharField(default='3 Months', max_length=100)),
                ('client_or_company', models.CharField(blank=True, max_length=150, null=True)),
                ('live_demo_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='portfolio.projectcategory')),
                ('technologies', models.ManyToManyField(related_name='projects', to='portfolio.technology')),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/screenshots/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='portfolio.project')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('proficiency_percentage', models.PositiveIntegerField(default=85)),
                ('icon_class', models.CharField(blank=True, max_length=60, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='portfolio.skillcategory')),
            ],
            options={
                'ordering': ['display_order', '-proficiency_percentage'],
            },
        ),
    ]
