# Generated by Django 5.1.15 on 2026-08-16 08:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('format_type', models.CharField(choices=[('EXCEL', 'Microsoft Excel (.xlsx / .xlsm)'), ('SQL', 'SQL Script Pack (.sql)'), ('PDF', 'PDF Document / Checklist'), ('DOCX', 'Word Template (.docx)'), ('ZIP', 'Toolkit Archive (.zip)')], default='EXCEL', max_length=10)),
                ('preview_image', models.ImageField(upload_to='store/previews/')),
                ('file_asset', models.FileField(upload_to='store/protected_assets/')),
                ('short_description', models.CharField(max_length=255)),
                ('full_description', models.TextField(help_text='Include details like formula structure, compatibility, and features.')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Set to 0.00 for free lead magnets.', max_digits=10)),
                ('currency', models.CharField(default='BDT', max_length=10)),
                ('downloads_count', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon_class', models.CharField(default='bi bi-folder-fill', max_length=60)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Store Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('customer_name', models.CharField(max_length=120)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=30)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(default='FREE_DOWNLOAD', max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('COMPLETED', 'Completed / Verified'), ('FAILED', 'Failed / Cancelled')], default='PENDING', max_length=20)),
                ('download_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='portfolio.digitalproduct')),
            ],
        ),
        migrations.AddField(
            model_name='digitalproduct',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='portfolio.storecategory'),
        ),
    ]
